name: test
recipe: lamp
config:
  webroot: web

services:
  appserver:
    build_as_root:
      - apt update
      - apt -y --no-install-recommends install collectd libmnl0
    config:
      vhosts: config/example/apache2/default.conf
    run_as_root:
      - collectd
    overrides:
      volumes:
        - ./config/example/apache2/status.conf:/etc/apache2/conf-enabled/status.conf
        - ./config/example/collectd/collectd.conf.d/common.conf:/etc/collectd/collectd.conf.d/10-common.conf
        - ./config/example/collectd/collectd.conf.d/appserver.conf:/etc/collectd/collectd.conf.d/20-appserver.conf
        - apache_logs_data:/var/log/apache2
    depends_on:
      - database

volumes:
  apache_logs_data: {}
