name: test
recipe: lamp
config:
  webroot: web

services:
  database:
    build_as_root:
      - apt update
      - apt -y --no-install-recommends install collectd libmariadb-dev libmnl0
    run_as_root:
      - collectd

volumes:
  apache_logs_data: {}
