name: test
recipe: lamp
config:
  webroot: web

services:
  database:
    overrides:
      volumes:
        - ./config/example/collectd/collectd.conf.d/common.conf:/etc/collectd/collectd.conf.d/10-common.conf
        - ./config/example/collectd/collectd.conf.d/database.conf:/etc/collectd/collectd.conf.d/20-database.conf

volumes:
  apache_logs_data: {}
