name: test
recipe: lamp
config:
  webroot: web

services:
  appserver:
    build_as_root:
      - apt update
      - apt -y --no-install-recommends install collectd libmnl0
    config:
      vhosts: config/example/apache2/default.conf
    # run_as_root:
    #   - collectd
    overrides:
      volumes:
        - ./config/example/apache2/status.conf:/etc/apache2/conf-enabled/status.conf
        - ./config/example/collectd/collectd.conf.d/common.conf:/etc/collectd/collectd.conf.d/10-common.conf
        - ./config/example/collectd/collectd.conf.d/appserver.conf:/etc/collectd/collectd.conf.d/20-appserver.conf
        - apache_logs_data:/var/log/apache2
    depends_on:
      - database

  alloy:
    type: lando
    api: 3
    services:
      image: grafana/alloy:latest
      command: /bin/alloy run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data --stability.level=experimental /etc/alloy
      ports:
        - '12345'
        - '4317'
        - '4318'
        - '9411'
        - '14268'
    overrides:
      volumes:
        # Make appserver logs available to Alloy.
        - apache_logs_data:/var/log/apache2

volumes:
  apache_logs_data: {}
